# Generated by Django 5.0.7 on 2024-08-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscription', '0002_subscription_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='permissions',
            field=models.ManyToManyField(limit_choices_to={'codename__in': ['Basic', 'advanced', 'pro'], 'content_type__app_label': 'subscription'}, to='auth.permission'),
        ),
    ]
